name: Auto Assign

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR
        uses: tibdex/auto-assign@v2
        with:
          assignees: |
            mpraes
          reviewers: |
            mpraes
