name: Teste de Ingestao Automatizado

on:
  pull_request:
    branches: [ main ]

jobs:
  avaliar:
    runs-on: self-hosted
    steps:
      - name: Checkout do codigo do participante
        uses: actions/checkout@v4

      - name: Executar Avaliacao Oficial no Servidor
        run: |
          PR_USER="${{ github.actor }}"
          chmod +x avaliador.sh
          ./avaliador.sh "$PR_USER"
